<?php
/**
 * @file
 * Overrides core contact form functionality
 */

use Drupal\contact\MessageForm;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\contact\ContactFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\contact\Entity\ContactForm;

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_form().
 */
function contact_ajax_form_contact_form_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\contact\ContactFormInterface $contact_form */
  $contact_form = $form_state->getFormObject()->getEntity();
  $form['ajax_enabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Ajax Form'),
    '#description' => t('Send this form using ajax.'),
    '#default_value' => $contact_form->getThirdPartySetting('contact_ajax', 'contact_ajax_enabled', FALSE),
  ];
  $form['#entity_builders'][] = 'contact_ajax_contact_form_form_builder';
}

/**
 * Entity builder for the contact form edit form with third party options.
 *
 * @see contact_ajax_test_form_contact_form_edit_form_alter()
 */
function contact_ajax_contact_form_form_builder($entity_type, ContactFormInterface $contact_form, &$form, FormStateInterface $form_state) {
  $contact_form->setThirdPartySetting('contact_ajax', 'contact_ajax_enabled', $form_state->getValue('ajax_enabled'));
}

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_form().
 */
function contact_ajax_form_contact_message_form_alter(&$form, &$form_state, $form_id) {
  /** @var \Drupal\Core\Entity\ContentEntityForm $form_object */
  $form_object = $form_state->getFormObject();
  /* @var \Drupal\contact\MessageInterface $contact_message */
  $contact_message = $form_object->getEntity();

  $contact_form = ContactForm::load($contact_message->bundle());

  /** @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface $form_mode */
  if ($form_object instanceof MessageForm) {

    $ajax_enabled = $contact_form->getThirdPartySetting('contact_ajax', 'contact_ajax_enabled', FALSE);

    if ($ajax_enabled) {
      $form['#prefix'] = '<div id="_contact_ajax_contact_form">';
      $form['#suffix'] = '</div>';

      $form['#ajaxsubmit'] = TRUE;
      $form['#submit'][] = 'contact_ajax_contact_site_form_submit';

      // adjust the form to use ajax submit
      $form['actions']['submit']['#ajax'] = array(
          'callback' => 'contact_ajax_contact_site_form_ajax_callback',
          'wrapper' => '_contact_ajax_contact_form',
          'method' => 'replace',
          'effect' => 'fade',
      );
    }
  }
}

/**
 * Submit handler for contact form.
 * @param type $form
 * @param type $form_state
 */
function contact_ajax_contact_site_form_submit($form, &$form_state) {
  // rebuild the form after submitted successfully
  $form_state['rebuild'] = TRUE;
  // try this if you want to reset the form item values
  $form_state['input'] = array();
}

/**
 * Ajax callback for contact form.
 * @param type $form
 * @param type $form_state
 * @return type
 */
function contact_ajax_contact_site_form_ajax_callback($form, &$form_state) {
  return $form;
}

/**
 * Returns contact form.
 * @return type
 */
function _contact_ajax_contact_form() {
}

